language: node_js
node_js:
  - lts/*
script:
  - npm run doc
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep-history: true
  edge: true
  on:
    branch: master